#!/bin/bash

# Base aliases that should be on every system

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias cp="cp -iv"
#             │└─ list copied files
#             └─ prompt before overwriting an existing file

alias mkdir="mkdir -pv"
#                   │└─ list created directories
#                   └─ create intermediate directories

alias mv="mv -iv"
#             │└─ list moved files
#             └─ prompt before overwriting an existing file

alias rm="rm -rf --"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias d="cd ~/Desktop"
alias e="vim --"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias p="cd ~/projects"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias t="tmux"
alias y="yarn"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Customizations

alias count-files="find . -maxdepth 1 -type f | wc -l"
alias count-folders="find . -mindepth 1 -maxdepth 1 -type d | wc -l"
alias count='echo "Files  : $(find . -maxdepth 1 -type f | wc -l)" && echo "Folders: $(find . -mindepth 1 -maxdepth 1 -type d | wc -l)"'
alias rm='rm_safe'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `Advanced Packaging Tool`

alias apti="sudo apt-get install"
alias aptr="sudo apt-get remove"
alias apts="sudo apt-cache search"
alias aptu="sudo apt-get update \
                && sudo apt-get upgrade"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update applications and CLTs.

alias u="sudo apt-get update \
            && sudo apt-get upgrade"
alias packages="find ./ -type f -name \"package.json\" -exec stat --format=\"%Y %n\" {} + | grep -v \"node_modules\" | sort -n | awk '{print strftime(\"%Y-%m-%d %H:%M:%S\", \$1), \$2}'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Network tools

alias local-ip='hostname -I | awk '\''{print $1}'\'''
alias myip='curl -s https://ipinfo.io/ip'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Raspberry Pi specific

alias pi-temp='vcgencmd measure_temp'
alias pi-throttle='vcgencmd get_throttled'
alias pi-version='cat /proc/device-tree/model'
